version: '3.8'

services:
  app:
    build: ./app
    container_name: fastapi_face_app
    restart: always
    environment:
      # Use o IP do host ou hostname do container do db se estiver na mesma rede
      DATABASE_URL: postgresql+psycopg2://faceuser:facepass@host.docker.internal:5432/facedb
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
