version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_face
    restart: always
    environment:
      POSTGRES_USER: faceuser
      POSTGRES_PASSWORD: facepass
      POSTGRES_DB: facedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
