services:
  app:
    build:
      context: .          # agora aponta para a raiz do projeto
    container_name: fastapi_face_app
    restart: always
    environment:
      DATABASE_URL: postgresql+psycopg2://faceuser:facepass@db:5432/facedb
    volumes:
      - ./app:/usr/src/app/app   # mantém sincronizado o código
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - fastapi-net

networks:
  fastapi-net:
    external: true
